@echo off

mkdir build >NUL 2>NUL
pushd build

REM for /f "delims=" %%i in ('llvm-config --cxxflags --ldflags --system-libs --libs core x86') do %%i

REM cl -nologo -Zi -EHsc ..\code\unamed.cpp
clang-cl -nologo -Zi ..\code\unamed.cpp -ID:\tools\llvm\include -std:c++14   /EHs-c- /GR- -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -link -LIBPATH:D:\tools\llvm\lib D:\tools\llvm\lib\LLVMNVPTXCodeGen.lib D:\tools\llvm\lib\LLVMNVPTXDesc.lib D:\tools\llvm\lib\LLVMNVPTXInfo.lib D:\tools\llvm\lib\LLVMAMDGPUDisassembler.lib D:\tools\llvm\lib\LLVMAMDGPUAsmParser.lib D:\tools\llvm\lib\LLVMAMDGPUCodeGen.lib D:\tools\llvm\lib\LLVMMIRParser.lib D:\tools\llvm\lib\LLVMAMDGPUDesc.lib D:\tools\llvm\lib\LLVMAMDGPUUtils.lib D:\tools\llvm\lib\LLVMAMDGPUInfo.lib D:\tools\llvm\lib\LLVMPasses.lib D:\tools\llvm\lib\LLVMObjCARCOpts.lib D:\tools\llvm\lib\LLVMHelloNew.lib D:\tools\llvm\lib\LLVMCoroutines.lib D:\tools\llvm\lib\LLVMipo.lib D:\tools\llvm\lib\LLVMInstrumentation.lib D:\tools\llvm\lib\LLVMVectorize.lib D:\tools\llvm\lib\LLVMLinker.lib D:\tools\llvm\lib\LLVMIRReader.lib D:\tools\llvm\lib\LLVMAsmParser.lib D:\tools\llvm\lib\LLVMFrontendOpenMP.lib D:\tools\llvm\lib\LLVMX86Disassembler.lib D:\tools\llvm\lib\LLVMX86AsmParser.lib D:\tools\llvm\lib\LLVMX86CodeGen.lib D:\tools\llvm\lib\LLVMCFGuard.lib D:\tools\llvm\lib\LLVMGlobalISel.lib D:\tools\llvm\lib\LLVMX86Desc.lib D:\tools\llvm\lib\LLVMX86Info.lib D:\tools\llvm\lib\LLVMMCDisassembler.lib D:\tools\llvm\lib\LLVMSelectionDAG.lib D:\tools\llvm\lib\LLVMAsmPrinter.lib D:\tools\llvm\lib\LLVMDebugInfoDWARF.lib D:\tools\llvm\lib\LLVMCodeGen.lib D:\tools\llvm\lib\LLVMTarget.lib D:\tools\llvm\lib\LLVMScalarOpts.lib D:\tools\llvm\lib\LLVMInstCombine.lib D:\tools\llvm\lib\LLVMAggressiveInstCombine.lib D:\tools\llvm\lib\LLVMTransformUtils.lib D:\tools\llvm\lib\LLVMBitWriter.lib D:\tools\llvm\lib\LLVMAnalysis.lib D:\tools\llvm\lib\LLVMProfileData.lib D:\tools\llvm\lib\LLVMObject.lib D:\tools\llvm\lib\LLVMTextAPI.lib D:\tools\llvm\lib\LLVMMCParser.lib D:\tools\llvm\lib\LLVMMC.lib D:\tools\llvm\lib\LLVMDebugInfoCodeView.lib D:\tools\llvm\lib\LLVMDebugInfoMSF.lib D:\tools\llvm\lib\LLVMBitReader.lib D:\tools\llvm\lib\LLVMCore.lib D:\tools\llvm\lib\LLVMRemarks.lib D:\tools\llvm\lib\LLVMBitstreamReader.lib D:\tools\llvm\lib\LLVMBinaryFormat.lib D:\tools\llvm\lib\LLVMSupport.lib D:\tools\llvm\lib\LLVMDemangle.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib

popd
